In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import r2_score as r2_score_sk
from Standard_Scaler import StandardScaler
from keras.models import load_model

In [2]:
model = load_model('model.h5')

In [3]:
data = pd.read_csv('Boston.csv')
data

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,1.23247,0.0,8.14,0.0,0.538,6.142,91.7,3.9769,4.0,307.0,21.0,396.90,18.72,15.2
1,0.02177,82.5,2.03,0.0,0.415,7.610,15.7,6.2700,2.0,348.0,14.7,395.38,3.11,42.3
2,4.89822,0.0,18.10,0.0,0.631,4.970,100.0,1.3325,24.0,666.0,20.2,375.52,3.26,50.0
3,0.03961,0.0,5.19,0.0,0.515,6.037,34.5,5.9853,5.0,224.0,20.2,396.90,8.01,21.1
4,3.69311,0.0,18.10,0.0,0.713,6.376,88.4,2.5671,24.0,666.0,20.2,391.43,14.65,17.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,3.47428,0.0,18.10,1.0,0.718,8.780,82.9,1.9047,24.0,666.0,20.2,354.55,5.29,21.9
502,0.07896,0.0,12.83,0.0,0.437,6.273,6.0,4.2515,5.0,398.0,18.7,394.92,6.78,24.1
503,1.83377,0.0,19.58,1.0,0.605,7.802,98.2,2.0407,5.0,403.0,14.7,389.61,1.92,50.0
504,0.35809,0.0,6.20,1.0,0.507,6.951,88.5,2.8617,8.0,307.0,17.4,391.70,9.71,26.7
505,2.92400,0.0,19.58,0.0,0.605,6.101,93.0,2.2834,5.0,403.0,14.7,240.16,9.81,25.0

In [8]:
X = data.drop(columns=["MEDV"]).to_numpy()[480:]
Y = data.MEDV.to_numpy()[480:]

In [9]:
scale = StandardScaler()

In [10]:
X_normal = scale.encoder(X)

In [11]:
Y_predict = model.predict(X_normal)
cur_result = K.get_value(r2_score(K.constant(Y), Y_predict))
expected_one = r2_score_sk(Y, Y_predict)

1/1 [==============================] - 0s 89ms/step

In [12]:
Y_decode = scale.decoder(Y_predict).ravel()

In [13]:
for yd,yr in zip(Y_decode,Y):
    print("Bashorat: ",yd,"\tHaqiqiy",yr)

Bashorat:  20.062754 	Haqiqiy 20.9
Bashorat:  24.241684 	Haqiqiy 28.1
Bashorat:  35.63308 	Haqiqiy 35.4
Bashorat:  9.569557 	Haqiqiy 10.2
Bashorat:  22.187897 	Haqiqiy 24.3
Bashorat:  38.602074 	Haqiqiy 43.1
Bashorat:  17.173111 	Haqiqiy 17.6
Bashorat:  12.143544 	Haqiqiy 15.4
Bashorat:  18.610508 	Haqiqiy 16.2
Bashorat:  18.117271 	Haqiqiy 27.1
Bashorat:  20.075775 	Haqiqiy 21.4
Bashorat:  19.811935 	Haqiqiy 21.5
Bashorat:  21.540184 	Haqiqiy 22.4
Bashorat:  25.442474 	Haqiqiy 25.0
Bashorat:  19.214949 	Haqiqiy 16.6
Bashorat:  18.968674 	Haqiqiy 18.6
Bashorat:  26.440145 	Haqiqiy 22.0
Bashorat:  37.83524 	Haqiqiy 42.8
Bashorat:  36.495346 	Haqiqiy 35.1
Bashorat:  19.018799 	Haqiqiy 21.5
Bashorat:  35.624363 	Haqiqiy 36.0
Bashorat:  36.211334 	Haqiqiy 21.9
Bashorat:  23.941254 	Haqiqiy 24.1
Bashorat:  48.47467 	Haqiqiy 50.0
Bashorat:  28.579689 	Haqiqiy 26.7
Bashorat:  19.72802 	Haqiqiy 25.0